# GitLab CI Automation for PantherX Packages
# Author: Franz Geffke <franz@pantherx.org>
# Version: 0.0.8

# GitLab provided templates
include:
  - template: SAST.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml

# Git submodules
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  - deploy

# Pack and upload to S3
deploy:
  stage: deploy
  image: alpine:latest
  script:
    - cd ../
    - apk add py-pip
    - pip install --user awscli
    - export PATH="$PATH:/root/.local/bin"
    - export AWS_ACCESS_KEY_ID=$(echo "$AWS_ACCESS_KEY_ID")
    - export AWS_SECRET_ACCESS_KEY=$(echo "$AWS_SECRET_ACCESS_KEY")
    - export AWS_DEFAULT_REGION=eu-central-1
    - export PACKAGE_NAME="$(echo $CI_PROJECT_NAME)_$(echo $CI_COMMIT_TAG).tgz"
    - tar --exclude="$CI_PROJECT_NAME/.git" -zcvf "$PACKAGE_NAME" "$CI_PROJECT_NAME"
    - aws s3 cp "$PACKAGE_NAME" s3://source-git-pantherx-org/
  only:
    - tags
  tags: [source]
