#pragma once

// #define ANDROID_APP_THEME   
// #define ANDROID_APP_ACCENT
// #define ANDROID_APP_FORGROUND
// #define ANDROID_APP_BACKGROUND
#define ANDROID_MATERIAL_THEME_PRIMARY_COLOR             "#103e69"
